import { BrandingConfig } from './types'
import { generateBrandThemeTokens } from './palette'

const defaultPrimaryColor = '#0B57D0'
const defaultSecondaryColor = '#4F46E5'
const defaultAccentColor = '#0284C7'
const defaultBorderRadius = 'medium'

const { lightTokens } = generateBrandThemeTokens(
  defaultPrimaryColor,
  defaultSecondaryColor,
  defaultAccentColor,
  defaultBorderRadius
)

export const DEFAULT_BRANDING: BrandingConfig = {
  organizationId: 'default',
  organizationName: 'Darion Workforce',
  legalName: 'Darion Workforce Solutions Private Limited',
  slug: 'default',
  appTitle: 'Darion Workforce',
  tagline: 'Enterprise Workforce Operations & Shift Management',
  logoLightUrl: null,
  logoDarkUrl: null,
  iconUrl: null,
  faviconUrl: null,
  loginBannerUrl: null,
  loginHeroTitle: 'Workforce Portal',
  loginHeroSubtitle: 'Sign in to access your attendance, daily tasks, and shift workspace',
  primaryColor: defaultPrimaryColor,
  secondaryColor: defaultSecondaryColor,
  accentColor: defaultAccentColor,
  fontFamily: 'Google Sans',
  borderRadiusStyle: defaultBorderRadius,
  supportEmail: 'payroll@darionworkforce.internal',
  supportPhone: null,
  termsUrl: null,
  privacyUrl: null,
  payslip: {
    legalName: 'Darion Workforce Solutions',
    taxId: 'GSTIN27AABCT1234F1Z5',
    cinNumber: 'U74999DL2024PTC123456',
    addressLine1: 'Workforce Operations & Shift Management Division',
    addressLine2: null,
    signatoryName: 'Darion HR & Payroll Operations',
    signatoryTitle: 'Authorized Signatory',
    signatureUrl: null,
    stampUrl: null,
    disclaimer: 'This is a computer-generated official payroll slip generated by the Workforce System and does not require physical signature under digital signature compliance.',
  },
  mfaIssuerName: 'Darion Workforce',
  featureFlags: {
    video_meets: true,
    daily_tasks: true,
    payroll: true,
    qr_verification: true,
    live_tab_counter: true,
  },
  cssVariables: lightTokens,
}
