-- ============================================================================
-- MULTI-TENANT WHITE-LABELING & BRANDING SYSTEM MIGRATION
-- ============================================================================

-- 1. Create Organizations Table
CREATE TABLE IF NOT EXISTS public.organizations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  legal_name TEXT,
  slug TEXT UNIQUE NOT NULL,
  custom_domain TEXT UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Trigger for organizations updated_at
DROP TRIGGER IF EXISTS update_organizations_updated_at ON public.organizations;
CREATE TRIGGER update_organizations_updated_at
  BEFORE UPDATE ON public.organizations
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- 2. Create Organization Branding Table
CREATE TABLE IF NOT EXISTS public.organization_branding (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL UNIQUE REFERENCES public.organizations(id) ON DELETE CASCADE,
  app_title TEXT NOT NULL DEFAULT 'Darion Workforce',
  tagline TEXT DEFAULT 'Enterprise Workforce Operations & Shift Management',
  logo_light_url TEXT,
  logo_dark_url TEXT,
  icon_url TEXT,
  favicon_url TEXT,
  login_banner_url TEXT,
  login_hero_title TEXT DEFAULT 'Workforce Portal',
  login_hero_subtitle TEXT DEFAULT 'Sign in to access your attendance, tasks, and shift workspace',
  primary_color TEXT NOT NULL DEFAULT '#0B57D0',
  secondary_color TEXT DEFAULT '#4F46E5',
  accent_color TEXT DEFAULT '#0284C7',
  font_family TEXT NOT NULL DEFAULT 'Google Sans',
  border_radius_style TEXT NOT NULL DEFAULT 'medium',
  support_email TEXT DEFAULT 'support@workforce.internal',
  support_phone TEXT,
  terms_url TEXT,
  privacy_url TEXT,
  tax_id TEXT,
  cin_number TEXT DEFAULT 'U74999DL2024PTC123456',
  address_line1 TEXT DEFAULT 'Workforce Operations & Shift Management Division',
  address_line2 TEXT,
  signatory_name TEXT DEFAULT 'Authorized Signatory',
  signatory_title TEXT DEFAULT 'Head of Human Resources & Payroll',
  signature_url TEXT,
  stamp_url TEXT,
  payslip_footer_disclaimer TEXT DEFAULT 'This is a computer-generated official payroll slip generated by the Workforce Management System and does not require physical signature under digital signature compliance.',
  mfa_issuer_name TEXT NOT NULL DEFAULT 'Darion Workforce',
  feature_flags JSONB NOT NULL DEFAULT '{"video_meets": true, "daily_tasks": true, "payroll": true, "qr_verification": true, "live_tab_counter": true}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Trigger for organization_branding updated_at
DROP TRIGGER IF EXISTS update_org_branding_updated_at ON public.organization_branding;
CREATE TRIGGER update_org_branding_updated_at
  BEFORE UPDATE ON public.organization_branding
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- 3. Add organization_id column to existing tables (with backwards compatibility)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id) ON DELETE SET NULL;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id) ON DELETE SET NULL;

DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'shifts') THEN
    ALTER TABLE public.shifts ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id) ON DELETE SET NULL;
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'daily_tasks') THEN
    ALTER TABLE public.daily_tasks ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id) ON DELETE SET NULL;
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'meets') THEN
    ALTER TABLE public.meets ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id) ON DELETE SET NULL;
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'leaves') THEN
    ALTER TABLE public.leaves ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id) ON DELETE SET NULL;
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'feedback') THEN
    ALTER TABLE public.feedback ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id) ON DELETE SET NULL;
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'payroll_records') THEN
    ALTER TABLE public.payroll_records ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id) ON DELETE SET NULL;
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'mfa_reset_requests') THEN
    ALTER TABLE public.mfa_reset_requests ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id) ON DELETE SET NULL;
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'notifications') THEN
    ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id) ON DELETE SET NULL;
  END IF;
END $$;

-- 4. Seed Default Organization & Branding for seamless zero-downtime transition
DO $$
DECLARE
  default_org_id UUID;
BEGIN
  -- Insert or fetch default organization
  INSERT INTO public.organizations (name, legal_name, slug, is_active)
  VALUES ('Darion Workforce', 'Darion Workforce Solutions Private Limited', 'default', true)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
  RETURNING id INTO default_org_id;

  -- Insert or update default branding
  INSERT INTO public.organization_branding (
    organization_id,
    app_title,
    tagline,
    primary_color,
    secondary_color,
    accent_color,
    support_email,
    cin_number,
    address_line1,
    signatory_name,
    signatory_title,
    mfa_issuer_name
  )
  VALUES (
    default_org_id,
    'Darion Workforce',
    'Enterprise Workforce Operations & Shift Management',
    '#0B57D0',
    '#4F46E5',
    '#0284C7',
    'payroll@darionworkforce.internal',
    'U74999DL2024PTC123456',
    'Workforce Operations & Shift Management Division',
    'Darion HR & Payroll Operations',
    'Authorized Signatory',
    'Darion Workforce'
  )
  ON CONFLICT (organization_id) DO NOTHING;

  -- Backfill existing profiles and attendance to default organization
  UPDATE public.profiles SET organization_id = default_org_id WHERE organization_id IS NULL;
  UPDATE public.attendance SET organization_id = default_org_id WHERE organization_id IS NULL;
END $$;

-- 5. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_organizations_slug ON public.organizations (slug);
CREATE INDEX IF NOT EXISTS idx_organizations_custom_domain ON public.organizations (custom_domain);
CREATE INDEX IF NOT EXISTS idx_org_branding_org_id ON public.organization_branding (organization_id);
CREATE INDEX IF NOT EXISTS idx_profiles_org_id ON public.profiles (organization_id);
CREATE INDEX IF NOT EXISTS idx_attendance_org_id ON public.attendance (organization_id);

-- 6. Enable Row Level Security (RLS)
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_branding ENABLE ROW LEVEL SECURITY;

-- 7. Policies for Organizations
DROP POLICY IF EXISTS "Public can view active organizations" ON public.organizations;
CREATE POLICY "Public can view active organizations"
  ON public.organizations FOR SELECT
  USING (is_active = true);

DROP POLICY IF EXISTS "Admins can manage organizations" ON public.organizations;
CREATE POLICY "Admins can manage organizations"
  ON public.organizations FOR ALL
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

-- 8. Policies for Organization Branding
DROP POLICY IF EXISTS "Anyone can view organization branding" ON public.organization_branding;
CREATE POLICY "Anyone can view organization branding"
  ON public.organization_branding FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Admins can update organization branding" ON public.organization_branding;
CREATE POLICY "Admins can update organization branding"
  ON public.organization_branding FOR ALL
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));
